-- 1:DataBase Exploration

-- Check the structure of Scheme of the data
SELECT * FROM INFORMATION_SCHEMA.TABLES


--Explore all the columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

--ALL COLUMNS FROM A SPECIFIC TABLE
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dim_customers'

SELECT * FROM dim_customers

--2:DIMENSION EXPLORAION

--Check all country from where the customers comes from
SELECT DISTINCT
country
FROM dim_customers

--Explore All Product Categories "The Major Divisions"
SELECT DISTINCT category,subcategory,product_name FROM dim_products
ORDER BY 1,2,3

--DATE EXPLORATION

--Identify the earliest and latest dates

--Find the date of the first and last order
--how many years of sales are avaliable

SELECT
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) AS Sales_Years
FROM fact_sales

--Find the youngest and the oldest customer
SELECT
MIN(birthdate) AS oldest_customer,
DATEDIFF(year,MIN(birthdate),GETDATE()) AS Oldest_age,
MAX(birthdate) AS youngest_customer,
DATEDIFF(year,MAX(birthdate),GETDATE()) AS Youngest_age
FROM dim_customers

--4:MEASURES EXPLORATION

-- Find the Total Sales
SELECT SUM(sales_amount) AS Total_sales FROM fact_sales

--Find how many items are sold
SELECT SUM(quantity) AS Total_quantity FROM fact_sales

--Find the average selling price
SELECT AVG(price) AS Avg_price FROM fact_sales

--Find the Total number of Orders
SELECT COUNT(DISTINCT order_number) AS Total_orders FROM fact_sales

--Find the total number of products
SELECT COUNT(product_name) AS Total_products FROM dim_products
SELECT COUNT(Distinct product_name) AS Total_products FROM dim_products

--Find the total number of customer
SELECT COUNT(DISTINCT customer_key) AS Total_Customer FROM dim_customers

--Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS Total_Customer FROM fact_sales

--As we can clearly see that all  of our registered customers placed an order.

--Generate Report that shows all key metrics of the business  (Do All things in one query)
SELECT 'Total Sales' AS measure_name, SUM(sales_amount)AS measure_value FROM fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM fact_sales
UNION ALL
SELECT 'Average Price',AVG(price) FROM fact_sales
UNION ALL
SELECT 'Total No. Orders', COUNT(Distinct order_number) FROM fact_sales
UNION ALL
SELECT 'Total Products',COUNT(DISTINCT product_name) FROM dim_products
UNION ALL 
SELECT 'Total No. of Customers' , COUNT(DISTINCT customer_key) FROM dim_customers

-- 5:MAGNITUDE

--Combine multiple values to generate useful insights

--Find the Total Number of Customers by Countries
SELECT
country,
COUNT(customer_key) AS Total_Customers
FROM dim_customers
GROUP BY country 
ORDER BY Total_Customers DESC

--Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS Total_Customers
FROM dim_customers
GROUP BY gender


--Find total products by category
SELECT
category,
COUNT(product_key) AS Total_Products
FROM dim_products
GROUP BY category
ORDER BY Total_Products DESC

--What is the average cost in each category
SELECT
category,
AVG(cost) AS AVG_COST
FROM dim_products
GROUP BY category
ORDER BY AVG_COST DESC

--What is the total Revenue generated by each category
SELECT 
p.category,
SUM(f.sales_amount) total_revenue
FROM fact_sales f
LEFT JOIN dim_products p
ON p.product_key=f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--What is the total revune generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
FROM fact_sales f 
LEFT JOIN dim_customers c 
ON c.customer_key=f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

--6:RANKING ANALYSIS

--Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM fact_sales f
LEFT JOIN dim_products p
ON p.product_key=f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

--Which are the 5 worst performance products in terms of sales
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM fact_sales f
LEFT JOIN dim_products p
ON p.product_key=f.product_key
GROUP BY p.product_name
ORDER BY total_revenue 

-- Use Window Function  to get top 5 products
SELECT *
FROM(
SELECT 
p.product_name,
SUM(f.sales_amount) total_revenue,
ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
FROM fact_sales f
LEFT JOIN dim_products p
ON p.product_key=f.product_key
GROUP BY p.product_name)t
WHERE rank_products<6
	
